type Step = {
    step: number;
    status: "PASS" | "FAIL";
    actual?: string;
    issueId?: number;
};

type Run = {
    date: string;
    steps: Step[];
};

type Regression = {
    product: string;
    suite: string;
    testCase: string;
    history: Run[];
};

export default function regressionToHtml(r: Regression) {
    return `
<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="utf-8" />
    <title>Regression report – ${r.testCase}</title>
    <link rel="stylesheet" href="/regression.css" />
</head>
<body>

<header>
    <h1>🔁 Regression report</h1>

    <section class="meta">
        <div><b>Product:</b> ${r.product}</div>
        <div><b>Suite:</b> ${r.suite}</div>
        <div><b>Test case:</b> ${r.testCase}</div>
    </section>
</header>

<main>
    ${r.history
            .map(
                (run, i) => `
    <section class="run">
        <h2>Run #${i + 1}</h2>
        <div class="date">${run.date}</div>

        <table>
            <thead>
                <tr>
                    <th>Step</th>
                    <th>Status</th>
                    <th>Actual result</th>
                    <th>Issue</th>
                </tr>
            </thead>
            <tbody>
                ${run.steps
                        .map(
                            s => `
                <tr class="${s.status.toLowerCase()}">
                    <td>${s.step}</td>
                    <td>${s.status}</td>
                    <td>${s.actual ?? ""}</td>
                    <td>
                        ${s.issueId
                                    ? `<a href="https://github.com/YOUR_ORG/YOUR_REPO/issues/${s.issueId}" target="_blank">
                                        #${s.issueId}
                                   </a>`
                                    : ""
                                }
                    </td>
                </tr>`
                        )
                        .join("")}
            </tbody>
        </table>
    </section>
    `
            )
            .join("")}
</main>

<footer>
    Generated by Tesztmenedzser
</footer>

</body>
</html>
`.trim();
}
